import type { Prisma } from "@prisma/client";
import { prisma } from "./prisma.js";

export type AuditClient = Prisma.TransactionClient | typeof prisma;

/** Canonical audit action vocabulary used across modules. */
export const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  SUBMIT: "SUBMIT",
  ACKNOWLEDGE: "ACKNOWLEDGE",
  COMPLETE: "COMPLETE",
  ASSIGN: "ASSIGN",
  UNASSIGN: "UNASSIGN",
  ARCHIVE: "ARCHIVE",
  REPLACE: "REPLACE",
  // Domain-specific (kept for existing trail continuity)
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  SALES_EXECUTIVE_CREATED: "SALES_EXECUTIVE_CREATED",
  SALES_EXECUTIVE_PROFILE_CREATED: "SALES_EXECUTIVE_PROFILE_CREATED",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  TEAM_MEMBER_ENDED: "TEAM_MEMBER_ENDED",
  PROFILE_CREATED: "PROFILE_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  COMMANDO_ASSIGNMENT_STARTED: "COMMANDO_ASSIGNMENT_STARTED",
  COMMANDO_ASSIGNMENT_ENDED: "COMMANDO_ASSIGNMENT_ENDED",
  COMMANDO_ASSIGNMENT_EXITED: "COMMANDO_ASSIGNMENT_EXITED",
  COMMANDO_ASSIGNMENT_TRANSFERRED: "COMMANDO_ASSIGNMENT_TRANSFERRED",
  INTERVENTION_OUTCOME_RECORDED: "INTERVENTION_OUTCOME_RECORDED",
  RECORD_ACKNOWLEDGED: "RECORD_ACKNOWLEDGED",
  INTERVENTION_GOAL_CREATED: "INTERVENTION_GOAL_CREATED",
  REFERRAL_SUBMITTED: "REFERRAL_SUBMITTED",
  REFERRAL_ACKNOWLEDGED: "REFERRAL_ACKNOWLEDGED",
  REFERRAL_IN_PROGRESS: "REFERRAL_IN_PROGRESS",
  REFERRAL_COMPLETED: "REFERRAL_COMPLETED",
  SWOT_CREATED: "SWOT_CREATED",
  SWOT_VISIBILITY_UPDATED: "SWOT_VISIBILITY_UPDATED",
  ACTIVITY_TYPE_CREATED: "ACTIVITY_TYPE_CREATED",
  ACTIVITY_TYPE_UPDATED: "ACTIVITY_TYPE_UPDATED",
  DAILY_LOG_CREATED: "DAILY_LOG_CREATED",
  DAILY_WORK_LOG_CREATED: "DAILY_WORK_LOG_CREATED",
  DAILY_WORK_LOG_UPDATED: "DAILY_WORK_LOG_UPDATED",
  DAILY_WORK_LOG_DELETED: "DAILY_WORK_LOG_DELETED",
  WEEKLY_REVIEW_CREATED: "WEEKLY_REVIEW_CREATED",
  WEEKLY_REVIEW_UPDATED: "WEEKLY_REVIEW_UPDATED",
  WEEKLY_REVIEW_SUBMITTED: "WEEKLY_REVIEW_SUBMITTED",
  WEEKLY_REVIEW_ACKNOWLEDGED: "WEEKLY_REVIEW_ACKNOWLEDGED",
  MONITORING_CATEGORY_CREATED: "MONITORING_CATEGORY_CREATED",
  MONITORING_CATEGORY_UPDATED: "MONITORING_CATEGORY_UPDATED",
  MONITORING_CHECKLIST_ITEM_CREATED: "MONITORING_CHECKLIST_ITEM_CREATED",
  MONITORING_CHECKLIST_ITEM_UPDATED: "MONITORING_CHECKLIST_ITEM_UPDATED",
  MONITORING_RECORD_CREATED: "MONITORING_RECORD_CREATED",
  SYNC_EVAL_CREATED: "SYNC_EVAL_CREATED",
  ROLE_ASSIGNMENT_CREATED: "ROLE_ASSIGNMENT_CREATED",
  ROLE_ASSIGNMENT_UPDATED: "ROLE_ASSIGNMENT_UPDATED",
  SUPPORT_TASK_CREATED: "SUPPORT_TASK_CREATED",
  SUPPORT_TASK_UPDATED: "SUPPORT_TASK_UPDATED",
  SUPPORT_TASK_STATUS_UPDATED: "SUPPORT_TASK_STATUS_UPDATED",
  SUPPORT_TASK_REASSIGNED: "SUPPORT_TASK_REASSIGNED",
  SUPPORT_TASK_PROGRESS_NOTE_ADDED: "SUPPORT_TASK_PROGRESS_NOTE_ADDED",
  SUPPORT_TASK_ATTACHMENT_ADDED: "SUPPORT_TASK_ATTACHMENT_ADDED",
  SUPPORT_TASK_ATTACHMENT_REMOVED: "SUPPORT_TASK_ATTACHMENT_REMOVED",
  SALES_SUPPORT_LINK_ASSIGNED: "SALES_SUPPORT_LINK_ASSIGNED",
  SALES_SUPPORT_LINK_ENDED: "SALES_SUPPORT_LINK_ENDED",
  EISENHOWER_TASK_CREATED: "EISENHOWER_TASK_CREATED",
  EISENHOWER_TASK_UPDATED: "EISENHOWER_TASK_UPDATED",
  EISENHOWER_TASK_STATUS_UPDATED: "EISENHOWER_TASK_STATUS_UPDATED",
  ACTION_ITEM_CREATED: "ACTION_ITEM_CREATED",
  ACTION_ITEM_UPDATED: "ACTION_ITEM_UPDATED",
  ACTION_ITEM_COMPLETED: "ACTION_ITEM_COMPLETED",
  ACTION_ITEM_EXPIRED: "ACTION_ITEM_EXPIRED",
  ACTION_ITEM_REPLACED: "ACTION_ITEM_REPLACED",
  ACTION_ITEM_ATTACHMENT_ADDED: "ACTION_ITEM_ATTACHMENT_ADDED",
  ACTION_ITEM_ATTACHMENT_REMOVED: "ACTION_ITEM_ATTACHMENT_REMOVED",
  FEEDBACK_CREATED: "FEEDBACK_CREATED",
  PERFORMANCE_EVALUATION_CREATED: "PERFORMANCE_EVALUATION_CREATED",
  TEAM_LEAD_WRITE_BLOCKED_DURING_INTERVENTION:
    "TEAM_LEAD_WRITE_BLOCKED_DURING_INTERVENTION",
  COMMANDO_REQUEST_SUBMITTED: "COMMANDO_REQUEST_SUBMITTED",
  REFERRAL_INFORMATION_PROVIDED: "REFERRAL_INFORMATION_PROVIDED",
  REFERRAL_REJECTED: "REFERRAL_REJECTED",
} as const;

export type WriteAuditLogInput = {
  actorId: string | null;
  action: string;
  entityType: string;
  entityId?: string | null;
  metadata?: Prisma.InputJsonValue;
};

/**
 * Append-only audit trail writer. Prefer passing a transaction client when
 * the business write runs inside `$transaction`.
 */
export async function writeAuditLog(
  input: WriteAuditLogInput,
  client: AuditClient = prisma,
): Promise<void> {
  await client.auditLog.create({
    data: {
      actorId: input.actorId,
      action: input.action,
      entityType: input.entityType,
      entityId: input.entityId ?? null,
      metadata: input.metadata ?? undefined,
    },
  });
}
